name: game-of-life
version: 1.0.0.0

dependencies:
  - base

executables:
  game-of-life-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - game-of-life == 1.0.0.0

library:
  exposed-modules: GameOfLife
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - vector
    - split

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - game-of-life
      - hspec
