name: transpose
version: 1.1.0.2

dependencies:
  - base

library:
  exposed-modules: Transpose
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - safe
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - transpose
      - hspec
